name: Adventures in CS
description: >
    Everyday dealings with CS things
about: >
    I am Bilal, a country hopping Ph.D student dealing with distributed systems and cloud computing. I did my Bachelors in Computer Engineering at COMSATS University, Islamabad Pakistan. My Masters in Distributed Computing from UPC, Barcelona and KTH, Stockholm. Currently I am doing my Ph.D in Distributed Computing at UCLouvain, Belgium and IST, Portugal. My research interests include but are not limited to Black-box optimization, Big data frameworks, large-scale distributed systems, cloud computing and  machine learning
master_repo: false
url: "http://adventuresincs.com"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname: mbilalce

rtl: false
owner:
  name:           Bilal
  avatar:         "https://avatars3.githubusercontent.com/u/6491549?s=400&u=4a8e20016ec5cf6cda129ccf711736af42a0dc9e&v=4"
  email:          "muhammad.bilal@uclouvain.be"
  # Social networking links used in footer. Update and remove as you like.
  twitter: mb_ce
  github: https://github.com/MBtech
  stackexchange: https://stackoverflow.com/users/3167229/mb-ce?tab=profile
  linkedin: https://www.linkedin.com/in/mbilalce/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
